# Render deployment configuration for GlückenKurs Bot
services:
  # FastAPI Web Server (для Stripe webhooks та оплати)
  - type: web
    name: gluckenkurs-web
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.web.server:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: DB_SCHEMA
        value: gluckenkurs
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL_GPT
        value: gpt-4o-mini
      - key: OPENAI_MODEL_TTS
        value: tts-1
      - key: OPENAI_MODEL_STT
        value: whisper-1
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_PRODUCT_ID
        sync: false
      - key: BASE_URL
        value: https://gluckenkurs-web.onrender.com
      - key: INTRO_CHANNEL_ID
        sync: false
      - key: PAID_CHANNEL_ID
        sync: false
      - key: REMINDER_DAYS
        value: 3
    healthCheckPath: /health

  # Telegram Bot Worker (фоновий процес)
  - type: worker
    name: gluckenkurs-bot
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/migrate_db.py && python -m app.bot.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: DB_SCHEMA
        value: gluckenkurs
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL_GPT
        value: gpt-4o-mini
      - key: OPENAI_MODEL_TTS
        value: tts-1
      - key: OPENAI_MODEL_STT
        value: whisper-1
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_PRODUCT_ID
        sync: false
      - key: BASE_URL
        value: https://gluckenkurs-web.onrender.com
      - key: INTRO_CHANNEL_ID
        sync: false
      - key: PAID_CHANNEL_ID
        sync: false
      - key: REMINDER_DAYS
        value: 3

# Примітка: DATABASE_URL буде автоматично взято з вашої існуючої PostgreSQL БД на Render
# DB_SCHEMA=gluckenkurs створить окрему схему для цього проекту
